version: '3'

services:
  php:
    image: php:8.1-cli
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

  composer:
    image: composer/composer
    volumes:
      - ./:/app
    command:
      - install